import Head from 'next/head'
import React from 'react'
import Navbar from '../../components/navbar'

const Developer = () => {
    return (
        <>
        <Head>
            <title> Developer Side </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar></Navbar>
        <div className='container-component'>
            <h3>
                Developer Side
            </h3>
        </div>

        </>
    )
}

export default Developer