import Head from 'next/head'
import React from 'react'
import Navbar from '../../components/navbar'
import { useEffect, useState } from 'react';
import { onAuthStateChanged, User } from 'firebase/auth';
import { authentication } from '@/components/lib/firebase';
import { DocumentData, onSnapshot } from 'firebase/firestore';
import { authCollectionRef }  from '@/components/lib/firebase-collection'
import { AccountProvider, useAccount } from '@/components/context/Account';
import Interaction from '@/components/process/Interaction';
import Feeds from '@/components/process/Feeds';

const HomeMain = () => {

    const { user } = useAccount()


    return (
        <>
            <Head>
                <title> Lazy-pot </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar></Navbar>
            <div className='container-component'>
                <div className="content-news" style={ user?.email && user.email.length > 0 ? {display:'block'} : {display:'none'}}>
                    
                </div>
                <div className="content-feeds">
                    <Feeds></Feeds>
                </div>
                <div className="content-interaction" style={ user?.email && user.email.length > 0 ? {display:'block'} : {display:'none'}}>
                    <Interaction></Interaction>
                </div>
            </div>
        </>
    )
}

export default HomeMain